import type { GameData, StreamingGame } from "./types";

function previews(screenshots: string[]) {
  return screenshots.map((src) => ({ kind: "image" as const, src }));
}

export const allGames: GameData[] = [
  {
    id: "game-001",
    developerId: "dev-001",
    title: "Wayward Warriors",
    slug: "wayward-warriors",
    description:
      "A fast-paced action RPG set in a mythical archipelago. Battle creatures from Indonesian legends and uncover ancient secrets hidden across floating islands.\n\nExplore vast temples, master elemental combat, and forge alliances with mythical spirits. Every island holds a new challenge.",
    genre: "Action RPG",
    platforms: ["PC", "Mac", "Steam Deck"],
    tags: ["Action", "RPG", "Mythology", "Single-player", "Adventure", "Indie"],
    coverImage: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=1200&q=80",
    horizontalCoverImage: "https://images.unsplash.com/photo-1511512578047-dfb367046420?w=1200&q=80",
    screenshots: [
      "https://images.unsplash.com/photo-1511512578047-dfb367046420?w=1200&q=80",
      "https://images.unsplash.com/photo-1493711662062-fa541adb3fc8?w=1200&q=80",
      "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=1200&q=80",
      "https://images.unsplash.com/photo-1538481199705-c710c4e965fc?w=1200&q=80",
    ],
    previews: [],
    trailerUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    gameUrl: "https://store.steampowered.com/app/waywardwarriors",
    websiteUrl: "https://waywardwarriors.game",
    campaignObjective: "Drive wishlist adds and demo downloads ahead of Steam Next Fest.",
    budgetMinDots: 3000,
    budgetMaxDots: 8000,
    streamerCount: 24,
    streamers: [
      { id: "s1", name: "PixelPioneer" },
      { id: "s2", name: "StreamQueen" },
      { id: "s3", name: "GameMaster99" },
    ],
    status: "PUBLISHED",
    publisher: "Nusantara Games",
    releaseDate: "2026-03-15",
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-01-01T00:00:00Z",
    developer: {
      id: "dev-001",
      studioName: "Nusantara Games",
      slug: "nusantara-games",
      bio: "Indie studio from Jakarta building games inspired by Southeast Asian folklore. Small team, big stories.",
      website: "https://nusantaragames.id",
    },
  },
  {
    id: "game-002",
    developerId: "dev-001",
    title: "Kopi & Kata",
    slug: "kopi-dan-kata",
    description:
      "A cozy narrative game about running a small coffee shop in Yogyakarta. Listen to customers' stories, brew drinks, and shape the neighborhood.\n\nEach cup tells a story. Meet travelers, artists, and locals — and discover how a simple coffee shop can change lives.",
    genre: "Simulation / Narrative",
    platforms: ["PC", "Mac"],
    tags: ["Simulation", "Narrative", "Cozy", "Casual", "Story Rich", "Indie"],
    coverImage: "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=1200&q=80",
    horizontalCoverImage: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=1200&q=80",
    screenshots: [
      "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=1200&q=80",
      "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=1200&q=80",
    ],
    previews: [],
    trailerUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    gameUrl: "https://store.steampowered.com/app/kopidankata",
    websiteUrl: "https://kopidankata.game",
    campaignObjective: "Reach cozy game audiences in SEA and Japan.",
    budgetMinDots: 2000,
    budgetMaxDots: 5000,
    streamerCount: 8,
    streamers: [
      { id: "s4", name: "CozyCatStreams" },
      { id: "s5", name: "NightOwlPlays" },
    ],
    status: "PUBLISHED",
    publisher: "Nusantara Games",
    releaseDate: "2026-05-01",
    createdAt: "2026-02-01T00:00:00Z",
    updatedAt: "2026-02-01T00:00:00Z",
    developer: {
      id: "dev-001",
      studioName: "Nusantara Games",
      slug: "nusantara-games",
      bio: "Indie studio from Jakarta building games inspired by Southeast Asian folklore. Small team, big stories.",
      website: "https://nusantaragames.id",
    },
  },
  {
    id: "game-003",
    developerId: "dev-002",
    title: "Neon Siege",
    slug: "neon-siege",
    description:
      "A cyberpunk tactical shooter where every run is different. Assemble your crew, breach corporate fortresses, and extract before the grid goes dark.\n\nProcedurally generated missions, deep squad customization, and a synthwave soundtrack that keeps your pulse racing.",
    genre: "Tactical Shooter",
    platforms: ["PC", "PlayStation 5", "Xbox Series X"],
    tags: ["Shooter", "Tactical", "Cyberpunk", "Multiplayer", "Sci-Fi", "Action"],
    coverImage: "https://images.unsplash.com/photo-1552820728-8b83bb6b2b26?w=1200&q=80",
    horizontalCoverImage: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=1200&q=80",
    screenshots: [
      "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=1200&q=80",
      "https://images.unsplash.com/photo-1538481199705-c710c4e965fc?w=1200&q=80",
      "https://images.unsplash.com/photo-1551103782-8ab07afd45c1?w=1200&q=80",
    ],
    previews: [],
    trailerUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    gameUrl: "https://store.steampowered.com/app/neonsiege",
    websiteUrl: "https://neonsiege.io",
    campaignObjective: "Build launch week momentum with 20+ streamers across PC and console.",
    budgetMinDots: 10000,
    budgetMaxDots: 25000,
    streamerCount: 36,
    streamers: [
      { id: "s6", name: "CyberAce" },
      { id: "s7", name: "TacticalTom" },
    ],
    status: "PUBLISHED",
    publisher: "Volt Hex Studios",
    releaseDate: "2026-07-20",
    createdAt: "2026-03-01T00:00:00Z",
    updatedAt: "2026-03-01T00:00:00Z",
    developer: {
      id: "dev-002",
      studioName: "Volt Hex Studios",
      slug: "volt-hex",
      bio: "Berlin-based indie team crafting tactical experiences with a neon aesthetic. Small team, big guns.",
      website: "https://volthex.io",
    },
  },
  {
    id: "game-004",
    developerId: "dev-003",
    title: "Phantom Protocol",
    slug: "phantom-protocol",
    description:
      "A stealth-action game set in a near-future Tokyo where corporate espionage is the new battlefield. Hack systems, manipulate drones, and vanish without a trace.\n\nEvery mission offers multiple paths — ghost through undetected or leave a trail of chaos.",
    genre: "Stealth / Action",
    platforms: ["PC", "PlayStation 5"],
    tags: ["Stealth", "Action", "Cyberpunk", "Sci-Fi", "Single-player", "Hacking"],
    coverImage: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=1200&q=80",
    horizontalCoverImage: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=1200&q=80",
    screenshots: [
      "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=1200&q=80",
      "https://images.unsplash.com/photo-1538481199705-c710c4e965fc?w=1200&q=80",
    ],
    previews: [],
    trailerUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    gameUrl: "https://store.steampowered.com/app/phantomprotocol",
    websiteUrl: "https://phantomprotocol.io",
    campaignObjective: "Build hype before the Tokyo Game Show reveal.",
    budgetMinDots: 6000,
    budgetMaxDots: 15000,
    streamerCount: 14,
    streamers: [
      { id: "s8", name: "NeonGhost" },
    ],
    status: "PUBLISHED",
    publisher: "Shinjuku Interactive",
    releaseDate: "2026-09-10",
    createdAt: "2026-03-15T00:00:00Z",
    updatedAt: "2026-03-15T00:00:00Z",
    developer: {
      id: "dev-003",
      studioName: "Shinjuku Interactive",
      slug: "shinjuku-interactive",
      bio: "Tokyo-based studio blending stealth mechanics with deep narrative. We make games about shadows and light.",
      website: "https://shinjukuinteractive.jp",
    },
  },
  {
    id: "game-005",
    developerId: "dev-004",
    title: "Realm Runners",
    slug: "realm-runners",
    description:
      "A roguelike dungeon crawler where you race through procedurally generated realms collecting artifacts and outrunning ancient guardians.\n\nNo two runs are the same. Combine relics, unlock characters, and chase leaderboard glory.",
    genre: "Roguelike / Action",
    platforms: ["PC", "Mac", "Nintendo Switch"],
    tags: ["Roguelike", "Action", "Dungeon Crawler", "Procedural", "Co-op", "Indie"],
    coverImage: "https://images.unsplash.com/photo-1538481199705-c710c4e965fc?w=1200&q=80",
    horizontalCoverImage: "https://images.unsplash.com/photo-1511512578047-dfb367046420?w=1200&q=80",
    screenshots: [
      "https://images.unsplash.com/photo-1538481199705-c710c4e965fc?w=1200&q=80",
      "https://images.unsplash.com/photo-1552820728-8b83bb6b2b26?w=1200&q=80",
    ],
    previews: [],
    trailerUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    gameUrl: "https://store.steampowered.com/app/realmrunners",
    websiteUrl: "https://realmrunners.game",
    campaignObjective: "Grow the speedrunning community around launch.",
    budgetMinDots: 2500,
    budgetMaxDots: 6000,
    streamerCount: 7,
    streamers: [
      { id: "s9", name: "SpeedDemon" },
    ],
    status: "PUBLISHED",
    publisher: "Forge & Ember",
    releaseDate: "2026-04-22",
    createdAt: "2026-02-15T00:00:00Z",
    updatedAt: "2026-02-15T00:00:00Z",
    developer: {
      id: "dev-004",
      studioName: "Forge & Ember",
      slug: "forge-ember",
      bio: "Two-person studio making infinitely replayable action games. We ship fast and iterate faster.",
      website: "https://forgeandember.dev",
    },
  },
  {
    id: "game-006",
    developerId: "dev-002",
    title: "Mecha Rivals",
    slug: "mecha-rivals",
    description:
      "A 3v3 mech brawler where pilots customize their machines mid-battle. Swap weapons, deploy drones, and outmaneuver your opponents in sprawling urban arenas.\n\nThe garage is your second battlefield — theorycraft builds between matches.",
    genre: "Fighting / Brawler",
    platforms: ["PC", "PlayStation 5", "Xbox Series X"],
    tags: ["Fighting", "Mecha", "Multiplayer", "Competitive", "Sci-Fi", "eSports"],
    coverImage: "https://images.unsplash.com/photo-1551103782-8ab07afd45c1?w=1200&q=80",
    horizontalCoverImage: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=1200&q=80",
    screenshots: [
      "https://images.unsplash.com/photo-1551103782-8ab07afd45c1?w=1200&q=80",
      "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=1200&q=80",
    ],
    previews: [],
    trailerUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    gameUrl: "https://store.steampowered.com/app/mecharivals",
    websiteUrl: "https://mecharivals.com",
    campaignObjective: "Drive competitive scene growth with tournament streams.",
    budgetMinDots: 8000,
    budgetMaxDots: 20000,
    streamerCount: 9,
    streamers: [
      { id: "s10", name: "BossFightBen" },
    ],
    status: "PUBLISHED",
    publisher: "Volt Hex Studios",
    releaseDate: "2026-08-05",
    createdAt: "2026-04-01T00:00:00Z",
    updatedAt: "2026-04-01T00:00:00Z",
    developer: {
      id: "dev-002",
      studioName: "Volt Hex Studios",
      slug: "volt-hex",
      bio: "Berlin-based indie team crafting tactical experiences with a neon aesthetic. Small team, big guns.",
      website: "https://volthex.io",
    },
  },
  {
    id: "game-007",
    developerId: "dev-005",
    title: "Echo Realms",
    slug: "echo-realms",
    description:
      "A survival horror set inside a derelict space station where the ghosts of its crew still linger. Solve environmental puzzles, manage limited resources, and decide who to trust.\n\nThe station remembers everything. And it's learning.",
    genre: "Survival Horror",
    platforms: ["PC", "PlayStation 5"],
    tags: ["Horror", "Survival", "Sci-Fi", "Puzzle", "Atmospheric", "Single-player"],
    coverImage: "https://images.unsplash.com/photo-1556438064-2d7646166914?w=1200&q=80",
    horizontalCoverImage: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=1200&q=80",
    screenshots: [
      "https://images.unsplash.com/photo-1556438064-2d7646166914?w=1200&q=80",
      "https://images.unsplash.com/photo-1552820728-8b83bb6b2b26?w=1200&q=80",
    ],
    previews: [],
    trailerUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    gameUrl: "https://store.steampowered.com/app/echorealms",
    websiteUrl: "https://echorealms.space",
    campaignObjective: "Build pre-launch dread with atmospheric streamer reveals.",
    budgetMinDots: 4000,
    budgetMaxDots: 9000,
    streamerCount: 11,
    streamers: [
      { id: "s11", name: "NightOwlPlays" },
    ],
    status: "PUBLISHED",
    publisher: "Void Lens Games",
    releaseDate: "2026-10-31",
    createdAt: "2026-05-01T00:00:00Z",
    updatedAt: "2026-05-01T00:00:00Z",
    developer: {
      id: "dev-005",
      studioName: "Void Lens Games",
      slug: "void-lens",
      bio: "Bristol-based studio focused on atmospheric horror experiences. We make games that stay with you long after the credits roll.",
      website: "https://voidlens.co.uk",
    },
  },
  {
    id: "game-008",
    developerId: "dev-004",
    title: "Crystal Vanguard",
    slug: "crystal-vanguard",
    description:
      "A colorful 3D platformer where you play as a crystal guardian protecting ancient temples from a corrupting blight. Master parkour movement, unlock elemental powers, and restore light to a dying world.\n\nDesigned for speedrunners and completionists alike.",
    genre: "Platformer",
    platforms: ["PC", "Nintendo Switch", "Steam Deck"],
    tags: ["Platformer", "Adventure", "Colorful", "Speedrun", "Family-Friendly", "Indie"],
    coverImage: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=1200&q=80",
    horizontalCoverImage: "https://images.unsplash.com/photo-1493711662062-fa541adb3fc8?w=1200&q=80",
    screenshots: [
      "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=1200&q=80",
      "https://images.unsplash.com/photo-1538481199705-c710c4e965fc?w=1200&q=80",
    ],
    previews: [],
    trailerUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    gameUrl: "https://store.steampowered.com/app/crystalvanguard",
    websiteUrl: "https://crystalvanguard.game",
    campaignObjective: "Showcase speedrun potential and collectible hunting.",
    budgetMinDots: 1500,
    budgetMaxDots: 4000,
    streamerCount: 8,
    streamers: [
      { id: "s12", name: "SpeedDemon" },
    ],
    status: "PUBLISHED",
    publisher: "Forge & Ember",
    releaseDate: "2026-06-15",
    createdAt: "2026-03-20T00:00:00Z",
    updatedAt: "2026-03-20T00:00:00Z",
    developer: {
      id: "dev-004",
      studioName: "Forge & Ember",
      slug: "forge-ember",
      bio: "Two-person studio making infinitely replayable action games. We ship fast and iterate faster.",
      website: "https://forgeandember.dev",
    },
  },
  {
    id: "game-009",
    developerId: "dev-006",
    title: "Drift Zone",
    slug: "drift-zone",
    description:
      "An arcade racing game set on neon-lit mountain passes. Chain drifts, earn style points, and compete in global leaderboards across 20 tracks inspired by real-world touge routes.\n\nFeel the G-force. Hear the tires scream. Own the mountain.",
    genre: "Racing / Arcade",
    platforms: ["PC", "PlayStation 5", "Xbox Series X"],
    tags: ["Racing", "Arcade", "Drifting", "Multiplayer", "Neon", "Competitive"],
    coverImage: "https://images.unsplash.com/photo-1493711662062-fa541adb3fc8?w=1200&q=80",
    horizontalCoverImage: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=1200&q=80",
    screenshots: [
      "https://images.unsplash.com/photo-1493711662062-fa541adb3fc8?w=1200&q=80",
      "https://images.unsplash.com/photo-1551103782-8ab07afd45c1?w=1200&q=80",
    ],
    previews: [],
    trailerUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    gameUrl: "https://store.steampowered.com/app/driftzone",
    websiteUrl: "https://driftzone.racing",
    campaignObjective: "Build drifting community and tournament scene.",
    budgetMinDots: 5000,
    budgetMaxDots: 12000,
    streamerCount: 6,
    streamers: [
      { id: "s13", name: "GearShift" },
    ],
    status: "PUBLISHED",
    publisher: "Downforce Interactive",
    releaseDate: "2026-05-28",
    createdAt: "2026-02-28T00:00:00Z",
    updatedAt: "2026-02-28T00:00:00Z",
    developer: {
      id: "dev-006",
      studioName: "Downforce Interactive",
      slug: "downforce",
      bio: "Melbourne-based team obsessed with car culture and arcade physics. If it drifts, we ship it.",
      website: "https://downforce.racing",
    },
  },
  {
    id: "game-010",
    developerId: "dev-007",
    title: "Shadow Circuit",
    slug: "shadow-circuit",
    description:
      "A Metroidvania set inside a malfunctioning AI simulation. Hack the system, unlock new traversal abilities, and uncover who trapped you here — and why.\n\nThe simulation is breaking. Reality bleeds through the cracks.",
    genre: "Metroidvania",
    platforms: ["PC", "Nintendo Switch", "PlayStation 5"],
    tags: ["Metroidvania", "Sci-Fi", "Exploration", "Pixel Art", "Atmospheric", "Indie"],
    coverImage: "https://images.unsplash.com/photo-1542751110-97427bbecf20?w=1200&q=80",
    horizontalCoverImage: "https://images.unsplash.com/photo-1556438064-2d7646166914?w=1200&q=80",
    screenshots: [
      "https://images.unsplash.com/photo-1542751110-97427bbecf20?w=1200&q=80",
      "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=1200&q=80",
    ],
    previews: [],
    trailerUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    gameUrl: "https://store.steampowered.com/app/shadowcircuit",
    websiteUrl: "https://shadowcircuit.dev",
    campaignObjective: "Target Metroidvania and indie game communities.",
    budgetMinDots: 1800,
    budgetMaxDots: 4500,
    streamerCount: 4,
    streamers: [
      { id: "s14", name: "BossFightBen" },
    ],
    status: "DRAFT",
    publisher: "Circuit Break Games",
    releaseDate: "2027-01-15",
    createdAt: "2026-05-10T00:00:00Z",
    updatedAt: "2026-05-10T00:00:00Z",
    developer: {
      id: "dev-007",
      studioName: "Circuit Break Games",
      slug: "circuit-break",
      bio: "Solo dev from Toronto building hand-crafted Metroidvanias with a sci-fi twist. One game at a time.",
      website: "https://circuitbreak.dev",
    },
  },
  {
    id: "game-011",
    developerId: "dev-008",
    title: "Warpath Tactics",
    slug: "warpath-tactics",
    description:
      "A turn-based tactical RPG set in a dieselpunk world at war. Command a squad of mercenaries through a branching campaign where every decision reshapes the front lines.\n\nPositioning matters. Morale matters. Victory is never guaranteed.",
    genre: "Tactical RPG",
    platforms: ["PC", "Mac"],
    tags: ["Tactical", "RPG", "Turn-Based", "Dieselpunk", "Strategy", "Single-player"],
    coverImage: "https://images.unsplash.com/photo-1538481199705-c710c4e965fc?w=1200&q=80",
    horizontalCoverImage: "https://images.unsplash.com/photo-1511512578047-dfb367046420?w=1200&q=80",
    screenshots: [
      "https://images.unsplash.com/photo-1538481199705-c710c4e965fc?w=1200&q=80",
      "https://images.unsplash.com/photo-1551103782-8ab07afd45c1?w=1200&q=80",
    ],
    previews: [],
    trailerUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    gameUrl: "https://store.steampowered.com/app/warpathtactics",
    websiteUrl: "https://warpathtactics.com",
    campaignObjective: "Reach strategy RPG fans and tabletop communities.",
    budgetMinDots: 3500,
    budgetMaxDots: 7000,
    streamerCount: 2,
    streamers: [
      { id: "s15", name: "TacticalTom" },
    ],
    status: "DRAFT",
    publisher: "Iron Banner Studios",
    releaseDate: "2026-12-01",
    createdAt: "2026-04-20T00:00:00Z",
    updatedAt: "2026-04-20T00:00:00Z",
    developer: {
      id: "dev-008",
      studioName: "Iron Banner Studios",
      slug: "iron-banner",
      bio: "Warsaw-based team of strategy veterans. We build worlds worth fighting for.",
      website: "https://ironbanner.pl",
    },
  },
  {
    id: "game-012",
    developerId: "dev-001",
    title: "Skybound Arena",
    slug: "skybound-arena",
    description:
      "A physics-based aerial combat game where players build and pilot custom airships. Battle in floating arenas, board enemy ships, and claim the skies.\n\nBuild. Fly. Conquer. The sky is your battlefield.",
    genre: "Action / Sandbox",
    platforms: ["PC", "Steam Deck"],
    tags: ["Sandbox", "Action", "Aerial Combat", "Building", "Multiplayer", "Physics"],
    coverImage: "https://images.unsplash.com/photo-1511512578047-dfb367046420?w=1200&q=80",
    horizontalCoverImage: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=1200&q=80",
    screenshots: [
      "https://images.unsplash.com/photo-1511512578047-dfb367046420?w=1200&q=80",
      "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=1200&q=80",
    ],
    previews: [],
    trailerUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    gameUrl: "https://store.steampowered.com/app/skyboundarena",
    websiteUrl: "https://skyboundarena.game",
    campaignObjective: "Showcase creative ship building and aerial battles.",
    budgetMinDots: 2200,
    budgetMaxDots: 5500,
    streamerCount: 3,
    streamers: [
      { id: "s16", name: "LootGoblin" },
    ],
    status: "DRAFT",
    publisher: "Nusantara Games",
    releaseDate: "2026-11-01",
    createdAt: "2026-05-15T00:00:00Z",
    updatedAt: "2026-05-15T00:00:00Z",
    developer: {
      id: "dev-001",
      studioName: "Nusantara Games",
      slug: "nusantara-games",
      bio: "Indie studio from Jakarta building games inspired by Southeast Asian folklore. Small team, big stories.",
      website: "https://nusantaragames.id",
    },
  },
  {
    id: "game-013",
    developerId: "dev-005",
    title: "Midnight Protocol",
    slug: "midnight-protocol",
    description:
      "A narrative-driven detective game set in a rain-soaked metropolis. Interrogate suspects, analyze crime scenes, and piece together a conspiracy that reaches the highest levels of power.\n\nEvery clue matters. Every lie has a tell.",
    genre: "Detective / Narrative",
    platforms: ["PC", "PlayStation 5", "Xbox Series X"],
    tags: ["Detective", "Narrative", "Noir", "Mystery", "Investigation", "Atmospheric"],
    coverImage: "https://images.unsplash.com/photo-1556438064-2d7646166914?w=1200&q=80",
    horizontalCoverImage: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=1200&q=80",
    screenshots: [
      "https://images.unsplash.com/photo-1556438064-2d7646166914?w=1200&q=80",
      "https://images.unsplash.com/photo-1542751110-97427bbecf20?w=1200&q=80",
    ],
    previews: [],
    trailerUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    gameUrl: "https://store.steampowered.com/app/midnightprotocol",
    websiteUrl: "https://midnightprotocol.game",
    campaignObjective: "Engage mystery and true-crime content creators.",
    budgetMinDots: 4500,
    budgetMaxDots: 10000,
    streamerCount: 16,
    streamers: [
      { id: "s17", name: "StoryTeller" },
    ],
    status: "PUBLISHED",
    publisher: "Void Lens Games",
    releaseDate: "2026-08-22",
    createdAt: "2026-04-10T00:00:00Z",
    updatedAt: "2026-04-10T00:00:00Z",
    developer: {
      id: "dev-005",
      studioName: "Void Lens Games",
      slug: "void-lens",
      bio: "Bristol-based studio focused on atmospheric horror experiences. We make games that stay with you long after the credits roll.",
      website: "https://voidlens.co.uk",
    },
  },
  {
    id: "game-014",
    developerId: "dev-006",
    title: "Thunder Rally",
    slug: "thunder-rally",
    description:
      "An off-road rally simulator with dynamic weather and terrain deformation. Race through deserts, forests, and snowy peaks in meticulously modeled vehicles.\n\nEvery bump tells a story.",
    genre: "Racing / Simulation",
    platforms: ["PC", "PlayStation 5", "Xbox Series X"],
    tags: ["Racing", "Simulation", "Off-Road", "Weather", "Realistic", "Multiplayer"],
    coverImage: "https://images.unsplash.com/photo-1551103782-8ab07afd45c1?w=1200&q=80",
    horizontalCoverImage: "https://images.unsplash.com/photo-1493711662062-fa541adb3fc8?w=1200&q=80",
    screenshots: [
      "https://images.unsplash.com/photo-1551103782-8ab07afd45c1?w=1200&q=80",
      "https://images.unsplash.com/photo-1493711662062-fa541adb3fc8?w=1200&q=80",
    ],
    previews: [],
    trailerUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    gameUrl: "https://store.steampowered.com/app/thunderrally",
    websiteUrl: "https://thunderrally.racing",
    campaignObjective: "Target sim-racing and automotive content creators.",
    budgetMinDots: 7000,
    budgetMaxDots: 18000,
    streamerCount: 19,
    streamers: [
      { id: "s18", name: "GearShift" },
    ],
    status: "PUBLISHED",
    publisher: "Downforce Interactive",
    releaseDate: "2026-09-05",
    createdAt: "2026-04-25T00:00:00Z",
    updatedAt: "2026-04-25T00:00:00Z",
    developer: {
      id: "dev-006",
      studioName: "Downforce Interactive",
      slug: "downforce",
      bio: "Melbourne-based team obsessed with car culture and arcade physics. If it drifts, we ship it.",
      website: "https://downforce.racing",
    },
  },
  {
    id: "game-015",
    developerId: "dev-003",
    title: "Sakura Drops",
    slug: "sakura-drops",
    description:
      "A meditative puzzle game about arranging falling cherry blossoms into beautiful patterns. Chill lo-fi soundtrack, no timers, no pressure — just pure flow state.\n\n100 levels of increasingly intricate arrangements.",
    genre: "Puzzle",
    platforms: ["PC", "Mac", "Nintendo Switch", "iOS", "Android"],
    tags: ["Puzzle", "Relaxing", "Minimalist", "Lo-Fi", "Casual", "Meditative"],
    coverImage: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=1200&q=80",
    horizontalCoverImage: "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=1200&q=80",
    screenshots: [
      "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=1200&q=80",
      "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=1200&q=80",
    ],
    previews: [],
    trailerUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    gameUrl: "https://store.steampowered.com/app/sakuradrops",
    websiteUrl: "https://sakuradrops.com",
    campaignObjective: "Reach cozy and chill gaming streamers.",
    budgetMinDots: 1000,
    budgetMaxDots: 3000,
    streamerCount: 5,
    streamers: [
      { id: "s19", name: "CozyCatStreams" },
    ],
    status: "PUBLISHED",
    publisher: "Shinjuku Interactive",
    releaseDate: "2026-04-01",
    createdAt: "2026-01-15T00:00:00Z",
    updatedAt: "2026-01-15T00:00:00Z",
    developer: {
      id: "dev-003",
      studioName: "Shinjuku Interactive",
      slug: "shinjuku-interactive",
      bio: "Tokyo-based studio blending stealth mechanics with deep narrative. We make games about shadows and light.",
      website: "https://shinjukuinteractive.jp",
    },
  },
  {
    id: "game-016",
    developerId: "dev-008",
    title: "Siegebreaker",
    slug: "siegebreaker",
    description:
      "A real-time strategy game where you command a medieval army besieging procedurally generated fortresses. Breach walls, manage supply lines, and adapt to enemy counterattacks.\n\nEvery siege is a puzzle. Every victory is earned.",
    genre: "Strategy",
    platforms: ["PC"],
    tags: ["Strategy", "RTS", "Medieval", "Procedural", "Siege", "Single-player"],
    coverImage: "https://images.unsplash.com/photo-1542751110-97427bbecf20?w=1200&q=80",
    horizontalCoverImage: "https://images.unsplash.com/photo-1538481199705-c710c4e965fc?w=1200&q=80",
    screenshots: [
      "https://images.unsplash.com/photo-1542751110-97427bbecf20?w=1200&q=80",
      "https://images.unsplash.com/photo-1538481199705-c710c4e965fc?w=1200&q=80",
    ],
    previews: [],
    trailerUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    gameUrl: "https://store.steampowered.com/app/siegebreaker",
    websiteUrl: "https://siegebreaker.com",
    campaignObjective: "Target strategy game YouTubers and RTS veterans.",
    budgetMinDots: 5500,
    budgetMaxDots: 14000,
    streamerCount: 28,
    streamers: [
      { id: "s20", name: "TacticalTom" },
    ],
    status: "PUBLISHED",
    publisher: "Iron Banner Studios",
    releaseDate: "2026-10-15",
    createdAt: "2026-05-01T00:00:00Z",
    updatedAt: "2026-05-01T00:00:00Z",
    developer: {
      id: "dev-008",
      studioName: "Iron Banner Studios",
      slug: "iron-banner",
      bio: "Warsaw-based team of strategy veterans. We build worlds worth fighting for.",
      website: "https://ironbanner.pl",
    },
  },
  {
    id: "game-017",
    developerId: "dev-004",
    title: "Glimmer Quest",
    slug: "glimmer-quest",
    description:
      "A charming action-adventure where you play as a tiny glowworm exploring a vast garden at night. Light up dark corners, befriend insects, and restore the garden's lost constellations.\n\nSmall hero. Big world. Brighter tomorrow.",
    genre: "Action-Adventure",
    platforms: ["PC", "Nintendo Switch"],
    tags: ["Adventure", "Exploration", "Charming", "Nature", "Family-Friendly", "Indie"],
    coverImage: "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=1200&q=80",
    horizontalCoverImage: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=1200&q=80",
    screenshots: [
      "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=1200&q=80",
      "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=1200&q=80",
    ],
    previews: [],
    trailerUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    gameUrl: "https://store.steampowered.com/app/glimmerquest",
    websiteUrl: "https://glimmerquest.game",
    campaignObjective: "Target family-friendly and cozy content creators.",
    budgetMinDots: 1200,
    budgetMaxDots: 3500,
    streamerCount: 12,
    streamers: [
      { id: "s21", name: "CozyCatStreams" },
    ],
    status: "PUBLISHED",
    publisher: "Forge & Ember",
    releaseDate: "2026-06-01",
    createdAt: "2026-03-05T00:00:00Z",
    updatedAt: "2026-03-05T00:00:00Z",
    developer: {
      id: "dev-004",
      studioName: "Forge & Ember",
      slug: "forge-ember",
      bio: "Two-person studio making infinitely replayable action games. We ship fast and iterate faster.",
      website: "https://forgeandember.dev",
    },
  },
  {
    id: "game-018",
    developerId: "dev-005",
    title: "Warden's Wake",
    slug: "wardens-wake",
    description:
      "A first-person survival horror where you patrol an abandoned prison island. Manage sanity, scavenge for supplies, and survive the night as something ancient stirs beneath the cells.\n\nThe lighthouse is your only safe haven. But the light is fading.",
    genre: "Survival Horror",
    platforms: ["PC", "PlayStation 5", "Xbox Series X"],
    tags: ["Horror", "Survival", "First-Person", "Atmospheric", "Psychological", "Single-player"],
    coverImage: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=1200&q=80",
    horizontalCoverImage: "https://images.unsplash.com/photo-1556438064-2d7646166914?w=1200&q=80",
    screenshots: [
      "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=1200&q=80",
      "https://images.unsplash.com/photo-1556438064-2d7646166914?w=1200&q=80",
    ],
    previews: [],
    trailerUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    gameUrl: "https://store.steampowered.com/app/wardenswake",
    websiteUrl: "https://wardenswake.horror",
    campaignObjective: "Create horror content for October launch window.",
    budgetMinDots: 6000,
    budgetMaxDots: 13000,
    streamerCount: 22,
    streamers: [
      { id: "s22", name: "NightOwlPlays" },
    ],
    status: "PUBLISHED",
    publisher: "Void Lens Games",
    releaseDate: "2026-10-25",
    createdAt: "2026-06-01T00:00:00Z",
    updatedAt: "2026-06-01T00:00:00Z",
    developer: {
      id: "dev-005",
      studioName: "Void Lens Games",
      slug: "void-lens",
      bio: "Bristol-based studio focused on atmospheric horror experiences. We make games that stay with you long after the credits roll.",
      website: "https://voidlens.co.uk",
    },
  },
  {
    id: "game-019",
    developerId: "dev-007",
    title: "Binary Bloom",
    slug: "binary-bloom",
    description:
      "A programming puzzle game disguised as a gardening simulator. Write simple code to automate your greenhouse — optimize water, light, and nutrients to grow the rarest digital flowers.\n\nLearn to code without realizing you're learning.",
    genre: "Puzzle / Educational",
    platforms: ["PC", "Mac", "iOS", "Android"],
    tags: ["Puzzle", "Programming", "Educational", "Casual", "Automation", "Chill"],
    coverImage: "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=1200&q=80",
    horizontalCoverImage: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=1200&q=80",
    screenshots: [
      "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=1200&q=80",
      "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=1200&q=80",
    ],
    previews: [],
    trailerUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    gameUrl: "https://store.steampowered.com/app/binarybloom",
    websiteUrl: "https://binarybloom.dev",
    campaignObjective: "Target dev-focused and educational content creators.",
    budgetMinDots: 1500,
    budgetMaxDots: 4000,
    streamerCount: 10,
    streamers: [
      { id: "s23", name: "IndieHunter" },
    ],
    status: "DRAFT",
    publisher: "Circuit Break Games",
    releaseDate: "2027-03-01",
    createdAt: "2026-06-10T00:00:00Z",
    updatedAt: "2026-06-10T00:00:00Z",
    developer: {
      id: "dev-007",
      studioName: "Circuit Break Games",
      slug: "circuit-break",
      bio: "Solo dev from Toronto building hand-crafted Metroidvanias with a sci-fi twist. One game at a time.",
      website: "https://circuitbreak.dev",
    },
  },
  {
    id: "game-020",
    developerId: "dev-003",
    title: "Ronin's Edge",
    slug: "ronins-edge",
    description:
      "A precision combat game with one-hit-kill mechanics set in feudal Japan. Master the katana, read your opponents, and strike at the exact moment of weakness.\n\nOne mistake. One chance. One perfect strike.",
    genre: "Action / Fighting",
    platforms: ["PC", "PlayStation 5"],
    tags: ["Action", "Samurai", "Precision", "Difficult", "Stylized", "Single-player"],
    coverImage: "https://images.unsplash.com/photo-1542751110-97427bbecf20?w=1200&q=80",
    horizontalCoverImage: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=1200&q=80",
    screenshots: [
      "https://images.unsplash.com/photo-1542751110-97427bbecf20?w=1200&q=80",
      "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=1200&q=80",
    ],
    previews: [],
    trailerUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    gameUrl: "https://store.steampowered.com/app/roninsedge",
    websiteUrl: "https://roninsedge.jp",
    campaignObjective: "Appeal to souls-like and precision combat content creators.",
    budgetMinDots: 4000,
    budgetMaxDots: 11000,
    streamerCount: 27,
    streamers: [
      { id: "s24", name: "BossFightBen" },
    ],
    status: "PUBLISHED",
    publisher: "Shinjuku Interactive",
    releaseDate: "2026-11-15",
    createdAt: "2026-06-15T00:00:00Z",
    updatedAt: "2026-06-15T00:00:00Z",
    developer: {
      id: "dev-003",
      studioName: "Shinjuku Interactive",
      slug: "shinjuku-interactive",
      bio: "Tokyo-based studio blending stealth mechanics with deep narrative. We make games about shadows and light.",
      website: "https://shinjukuinteractive.jp",
    },
  },
  {
    id: "game-021",
    developerId: "dev-002",
    title: "Gridfall",
    slug: "gridfall",
    description:
      "A vertical slice of competitive PvPvE extraction. Drop into procedurally generated megastructures, loot advanced tech, fight rival squads, and extract before the grid collapses.\n\nRisk it all. Go deeper. Extract richer.",
    genre: "Extraction Shooter",
    platforms: ["PC"],
    tags: ["Shooter", "Extraction", "PvPvE", "Competitive", "Sci-Fi", "Multiplayer"],
    coverImage: "https://images.unsplash.com/photo-1552820728-8b83bb6b2b26?w=1200&q=80",
    horizontalCoverImage: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=1200&q=80",
    screenshots: [
      "https://images.unsplash.com/photo-1552820728-8b83bb6b2b26?w=1200&q=80",
      "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=1200&q=80",
    ],
    previews: [],
    trailerUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    gameUrl: "https://store.steampowered.com/app/gridfall",
    websiteUrl: "https://gridfall.io",
    campaignObjective: "Build extraction shooter community with squad streamers.",
    budgetMinDots: 15000,
    budgetMaxDots: 25000,
    streamerCount: 48,
    streamers: [
      { id: "s25", name: "SiegeQueen" },
    ],
    status: "PUBLISHED",
    publisher: "Volt Hex Studios",
    releaseDate: "2026-12-10",
    createdAt: "2026-07-01T00:00:00Z",
    updatedAt: "2026-07-01T00:00:00Z",
    developer: {
      id: "dev-002",
      studioName: "Volt Hex Studios",
      slug: "volt-hex",
      bio: "Berlin-based indie team crafting tactical experiences with a neon aesthetic. Small team, big guns.",
      website: "https://volthex.io",
    },
  },
  {
    id: "game-022",
    developerId: "dev-006",
    title: "Apex Kart",
    slug: "apex-kart",
    description:
      "A chaotic kart racer with weapons, boost chains, and dynamically changing tracks. Race through volcanoes, underwater cities, and space stations — all in one lap.\n\nFirst to the finish wins. Last place gets the blue shell.",
    genre: "Racing / Party",
    platforms: ["PC", "Nintendo Switch", "PlayStation 5", "Xbox Series X"],
    tags: ["Racing", "Party", "Kart", "Multiplayer", "Chaotic", "Family-Friendly"],
    coverImage: "https://images.unsplash.com/photo-1493711662062-fa541adb3fc8?w=1200&q=80",
    horizontalCoverImage: "https://images.unsplash.com/photo-1551103782-8ab07afd45c1?w=1200&q=80",
    screenshots: [
      "https://images.unsplash.com/photo-1493711662062-fa541adb3fc8?w=1200&q=80",
      "https://images.unsplash.com/photo-1551103782-8ab07afd45c1?w=1200&q=80",
    ],
    previews: [],
    trailerUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    gameUrl: "https://store.steampowered.com/app/apexkart",
    websiteUrl: "https://apexkart.racing",
    campaignObjective: "Target party game and variety streamers.",
    budgetMinDots: 3000,
    budgetMaxDots: 8000,
    streamerCount: 33,
    streamers: [
      { id: "s1", name: "PixelPioneer" },
    ],
    status: "PUBLISHED",
    publisher: "Downforce Interactive",
    releaseDate: "2026-07-15",
    createdAt: "2026-04-15T00:00:00Z",
    updatedAt: "2026-04-15T00:00:00Z",
    developer: {
      id: "dev-006",
      studioName: "Downforce Interactive",
      slug: "downforce",
      bio: "Melbourne-based team obsessed with car culture and arcade physics. If it drifts, we ship it.",
      website: "https://downforce.racing",
    },
  },
  {
    id: "game-023",
    developerId: "dev-008",
    title: "Verdant Empires",
    slug: "verdant-empires",
    description:
      "A 4X strategy game where you lead a civilization from the Stone Age to the stars. Research technologies, forge alliances, and shape your empire's destiny across millennia.\n\nHistory is yours to write. The future is yours to build.",
    genre: "4X Strategy",
    platforms: ["PC", "Mac"],
    tags: ["Strategy", "4X", "Historical", "Empire Building", "Deep", "Single-player"],
    coverImage: "https://images.unsplash.com/photo-1538481199705-c710c4e965fc?w=1200&q=80",
    horizontalCoverImage: "https://images.unsplash.com/photo-1511512578047-dfb367046420?w=1200&q=80",
    screenshots: [
      "https://images.unsplash.com/photo-1538481199705-c710c4e965fc?w=1200&q=80",
      "https://images.unsplash.com/photo-1511512578047-dfb367046420?w=1200&q=80",
    ],
    previews: [],
    trailerUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    gameUrl: "https://store.steampowered.com/app/verdantempires",
    websiteUrl: "https://verdantempires.com",
    campaignObjective: "Reach grand strategy and Civ-like content communities.",
    budgetMinDots: 9000,
    budgetMaxDots: 20000,
    streamerCount: 15,
    streamers: [
      { id: "s3", name: "GameMaster99" },
    ],
    status: "PUBLISHED",
    publisher: "Iron Banner Studios",
    releaseDate: "2027-02-20",
    createdAt: "2026-07-15T00:00:00Z",
    updatedAt: "2026-07-15T00:00:00Z",
    developer: {
      id: "dev-008",
      studioName: "Iron Banner Studios",
      slug: "iron-banner",
      bio: "Warsaw-based team of strategy veterans. We build worlds worth fighting for.",
      website: "https://ironbanner.pl",
    },
  },
  {
    id: "game-024",
    developerId: "dev-007",
    title: "Songweaver",
    slug: "songweaver",
    description:
      "A rhythm RPG where every battle is a musical duel. Time your attacks to the beat, compose your own combos, and defeat the Silence that threatens to mute the world.\n\nYour controller is an instrument. Your battles are symphonies.",
    genre: "Rhythm / RPG",
    platforms: ["PC", "Nintendo Switch"],
    tags: ["Rhythm", "RPG", "Music", "Stylized", "Story-Rich", "Indie"],
    coverImage: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=1200&q=80",
    horizontalCoverImage: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=1200&q=80",
    screenshots: [
      "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=1200&q=80",
      "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=1200&q=80",
    ],
    previews: [],
    trailerUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    gameUrl: "https://store.steampowered.com/app/songweaver",
    websiteUrl: "https://songweaver.game",
    campaignObjective: "Appeal to rhythm game and music content creators.",
    budgetMinDots: 2500,
    budgetMaxDots: 6000,
    streamerCount: 18,
    streamers: [
      { id: "s2", name: "StreamQueen" },
    ],
    status: "PUBLISHED",
    publisher: "Circuit Break Games",
    releaseDate: "2026-09-20",
    createdAt: "2026-05-20T00:00:00Z",
    updatedAt: "2026-05-20T00:00:00Z",
    developer: {
      id: "dev-007",
      studioName: "Circuit Break Games",
      slug: "circuit-break",
      bio: "Solo dev from Toronto building hand-crafted Metroidvanias with a sci-fi twist. One game at a time.",
      website: "https://circuitbreak.dev",
    },
  },
  {
    id: "game-025",
    developerId: "dev-001",
    title: "Archipelago Legacy",
    slug: "archipelago-legacy",
    description:
      "An open-world adventure set across a vast archipelago inspired by Indonesian mythology. Sail between islands, uncover ancient ruins, and battle colossal guardians in epic encounters.\n\nThe ocean remembers. The islands whisper. Your legacy awaits.",
    genre: "Action-Adventure",
    platforms: ["PC", "PlayStation 5", "Xbox Series X"],
    tags: ["Open-World", "Adventure", "Mythology", "Sailing", "Epic", "AAA-Scale Indie"],
    coverImage: "https://images.unsplash.com/photo-1511512578047-dfb367046420?w=1200&q=80",
    horizontalCoverImage: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=1200&q=80",
    screenshots: [
      "https://images.unsplash.com/photo-1511512578047-dfb367046420?w=1200&q=80",
      "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=1200&q=80",
    ],
    previews: [],
    trailerUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    gameUrl: "https://store.steampowered.com/app/archipelagolegacy",
    websiteUrl: "https://archipelagolegacy.game",
    campaignObjective: "Massive pre-launch campaign targeting open-world and mythology fans.",
    budgetMinDots: 20000,
    budgetMaxDots: 25000,
    streamerCount: 42,
    streamers: [
      { id: "s6", name: "CyberAce" },
    ],
    status: "ARCHIVED",
    publisher: "Nusantara Games",
    releaseDate: "2026-01-10",
    createdAt: "2025-10-01T00:00:00Z",
    updatedAt: "2026-03-01T00:00:00Z",
    developer: {
      id: "dev-001",
      studioName: "Nusantara Games",
      slug: "nusantara-games",
      bio: "Indie studio from Jakarta building games inspired by Southeast Asian folklore. Small team, big stories.",
      website: "https://nusantaragames.id",
    },
  },
];

for (const game of allGames) {
  if (game.previews.length === 0) {
    (game as { previews: typeof game.previews }).previews = previews(game.screenshots);
  }
}

const gamesBySlug: Record<string, GameData> = {};
for (const game of allGames) {
  gamesBySlug[game.slug] = game;
}

export function getAllGames(): GameData[] {
  return allGames;
}

export function getGame(slug: string): GameData | undefined {
  return gamesBySlug[slug];
}

export const streamingGames: StreamingGame[] = allGames
  .filter((g) => g.status === "PUBLISHED")
  .map((g) => ({
    title: g.title,
    slug: g.slug,
    coverImage: g.coverImage,
    streamerCount: g.streamerCount,
  }));

export function getStreamingToday(): StreamingGame[] {
  return streamingGames;
}
